wip: tweaks/hacks from v3 init

diff --git a/home/.chezmoiscripts/run_once_after_45_gnome_extensions.sh.tmpl b/home/.chezmoiscripts/run_once_after_45_gnome_extensions.sh.tmpl
--- a/home/.chezmoiscripts/run_once_after_45_gnome_extensions.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_after_45_gnome_extensions.sh.tmpl
@@ -1,8 +1,5 @@
 #!/bin/env bash
 
-# shellcheck disable=SC1054,SC1083
-{{ if regexMatch "^gnome" .desktop_session }}
-
 echo '
  ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
 ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
@@ -18,66 +15,65 @@ echo '
    ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝
 '
 _gnome_extensions_installed=(
-  "nightthemeswitcher@romainvigier.fr"
-  "pano@elhan.io"
-  "paperwm@paperwm.github.com"
-  "user-theme@gnome-shell-extensions.gcampax.github.com"
-  "Vitals@CoreCoding.com"
-  "weatheroclock@CleoMenezesJr.github.io"
+	"nightthemeswitcher@romainvigier.fr"
+	"pano@elhan.io"
+	"paperwm@paperwm.github.com"
+	"user-theme@gnome-shell-extensions.gcampax.github.com"
+	"Vitals@CoreCoding.com"
+	"weatheroclock@CleoMenezesJr.github.io"
 )
 
 _gnome_extensions_removed=(
-  "freon@UshakovVasilii_Github.yahoo.com"
+	"freon@UshakovVasilii_Github.yahoo.com"
 )
 
 function dbhostexec() {
-  if ([[ -f /run/.containerenv ]] || [[ -f /.dockerenv ]]) &&
-    [[ $(command -v distrobox-host-exec) ]]; then
-    distrobox-host-exec "${@}"
-  else
-    "${@}"
-  fi
+	if ([[ -f /run/.containerenv ]] || [[ -f /.dockerenv ]]) &&
+		[[ $(command -v distrobox-host-exec) ]]; then
+		distrobox-host-exec "${@}"
+	else
+		"${@}"
+	fi
 }
 
 if dbhostexec which pyenv &>/dev/null; then
-  export PYENV_VERSION=system
+	export PYENV_VERSION=system
 fi
 
 function _install_gnome_extensions() {
-  if ! dbhostexec which gext &>/dev/null; then
+	if ! dbhostexec which gext &>/dev/null; then
 
-    if [[ $(cat /proc/version | grep arch) ]]; then
+		if [[ $(cat /proc/version | grep arch) ]]; then
 
-      if ! dbhostexec which pipx &>/dev/null; then
-        printf "Missing pipx! Cannot install gext\n"
-        return 1
-      fi
+			if ! dbhostexec which pipx &>/dev/null; then
+				printf "Missing pipx! Cannot install gext\n"
+				return 1
+			fi
 
-      dbhostexec pipx install gnome-extensions-cli
-      dbhostexec pipx runpip gnome-extensions-cli install pygobject
+			dbhostexec pipx install gnome-extensions-cli
+			dbhostexec pipx runpip gnome-extensions-cli install pygobject
 
-    else
-      dbhostexec pip install --upgrade gnome-extensions-cli
-    fi
+		else
+			dbhostexec pip install --upgrade gnome-extensions-cli
+		fi
 
-  else
-    echo "🚀 gext already installed!"
-  fi
+	else
+		echo "🚀 gext already installed!"
+	fi
 
-  _gext="$(dbhostexec which gext)"
+	_gext="$(dbhostexec which gext)"
 
-  for _ext in "${_gnome_extensions_removed[@]}"; do
-    dbhostexec $_gext uninstall "${_ext}"
-  done
+	for _ext in "${_gnome_extensions_removed[@]}"; do
+		dbhostexec $_gext uninstall "${_ext}"
+	done
 
-  for _ext in "${_gnome_extensions_installed[@]}"; do
-    dbhostexec $_gext install "${_ext}"
-  done
+	for _ext in "${_gnome_extensions_installed[@]}"; do
+		dbhostexec $_gext install "${_ext}"
+	done
 }
 
 _install_gnome_extensions
 
 # shellcheck disable=SC1056,SC1072,SC1083,SC1009,SC1073
-{{ end -}}
 
 # vi: ft=bash
